Fri, 11 May 2018 15:20:14 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Fri, 11 May 2018 15:20:14 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 65536
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:20 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:20 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:20 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:21 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:21 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:21 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:22 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 169, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:22 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 169, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:22 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 169, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:22 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 169, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 15:20:22 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:22 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:22 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:22 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:22 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 169, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 imgcut.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 252, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 3833444' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:23 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 169, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:23 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 169, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:23 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '6:9338640'
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:23 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '056:96:2386'
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:23 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '066:96:2386'
Fri, 11 May 2018 15:20:23 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:23 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:23 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:23 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:23 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '066:96:2328'
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:24 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '066:96:2328'
Fri, 11 May 2018 15:20:24 imgcut.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 252, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 6:2648006806696' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:24 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:24 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:24 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:24 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '244:66300'
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:25 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '48604:66400'
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 252, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 0096:11:29:2' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 15:20:25 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:25 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: '48604:66400'
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:25 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:25 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:25 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:26 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:26 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:26 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 imgcut.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 252, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 :29:3' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:27 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 221, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:27 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 221, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:27 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 221, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 11 May 2018 15:20:27 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:27 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:27 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:27 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:27 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 221, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:28 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 221, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 app_thread.py[line:230] ERROR 识别价格失败
Fri, 11 May 2018 15:20:28 app_thread.py[line:231] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 215, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 228, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 221, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 11 May 2018 15:20:28 imgcut.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 252, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 :68:944' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:28 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:28 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:28 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:29 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:29 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:29 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:30 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:30 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:30 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:31 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:31 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:31 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:31 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:31 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:31 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:31 imgcut.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 252, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 44444' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 15:20:31 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:31 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:31 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 15:20:31 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 15:20:31 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 15:20:31 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
