Fri, 22 Jun 2018 05:06:00 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:00 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:00 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:00 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:00 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:00 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:01 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:01 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:01 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:01 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Fri, 22 Jun 2018 05:06:01 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:255] ERROR 识别价格失败
Fri, 22 Jun 2018 05:06:01 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
