Mon, 12 Mar 2018 14:17:40 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:40 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 65536
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:40 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:40 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:40 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:41 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:41 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:41 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:42 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:42 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:42 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:43 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:43 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:43 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:44 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:44 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:44 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:45 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:45 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:45 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:46 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:46 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:46 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:47 imgcut.py[line:309] ERROR cut_img 这里出错
Mon, 12 Mar 2018 14:17:47 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:108] ERROR 刷新失败
Mon, 12 Mar 2018 14:17:47 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:54 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:55 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:56 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:57 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:58 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:17:59 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:00 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:01 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:02 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:03 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Mon, 12 Mar 2018 14:18:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
