Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:08 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:08 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:08 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:08 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:08 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:08 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:08 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:08 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:08 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:08 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:08 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:08 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:08 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:08 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:08 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:08 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:08 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:09 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:09 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:09 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:09 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:09 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:254] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 240, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:10 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:10 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:10 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:10 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:10 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:10 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:10 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:11 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:11 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:11 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:228] ERROR 识别价格失败
Fri, 25 May 2018 18:12:11 app_thread.py[line:229] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 516, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 224, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 165, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:11 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:11 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:11 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:11 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:11 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:12 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:12 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:12 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:12 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:12 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:13 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:13 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:13 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:13 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:13 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:14 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:14 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:14 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:14 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:15 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:15 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:15 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:15 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:16 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:16 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:16 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:16 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:16 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:17 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:17 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:17 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:17 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:17 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:18 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:18 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:18 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:18 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:19 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:19 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:19 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:19 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:19 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:19 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:19 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:19 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:19 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:19 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:19 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:19 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:19 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:19 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:19 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:19 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:20 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:20 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:20 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:20 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:20 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:21 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:21 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:21 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:21 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:21 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:22 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:22 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:22 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:22 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:23 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:23 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:23 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:23 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:23 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:24 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:24 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
Fri, 25 May 2018 18:12:24 imgcut.py[line:437] INFO 截图成功
Fri, 25 May 2018 18:12:24 imgcut.py[line:439] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 25 May 2018 18:12:24 imgcut.py[line:441] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 25 May 2018 18:12:24 app_thread.py[line:719] ERROR 提交出错
Fri, 25 May 2018 18:12:24 app_thread.py[line:720] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 400, in run
    strategy_type = get_dick('strategy_type')
NameError: name 'get_dick' is not defined
